data :
  name: BTAD 
  data_dir: datasets/BTAD
  category: '01'   #['carpet', 'bottle', 'hazelnut', 'leather', 'cable', 'capsule', 'grid', 'pill', 'transistor', 'metal_nut', 'screw','toothbrush', 'zipper', 'tile', 'wood']    #['01','02','03']  
  image_size: 256 
  batch_size: 8
  mask : True 
  imput_channel : 3

model:
  checkpoint_dir: checkpoints/BTAD
  resnet: wide_resnet101_2
  learning_rate: 3e-4 
  weight_decay: 0.05 
  epochs: 2001
  epochs_checkpoint: 100
  diffusion_steps: 1000
  beta_start : 0.0001
  beta_end : 0.02 
  device: 'cuda'
  num_workers : 8